<?php

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Path\PathMatcher;
use Drupal\Core\Url;

//adding livechat code when conditions are met
function livechat_page_attachments_alter(array &$page) {
 
  $config = \Drupal::config('livechat.settings');
  
  $path = \Drupal::service('path.current')->getPath();
  
  if (empty($config->get('licence_number'))) {
    return;
  }

  $is_admin_page = true;
  if(!_livechat_active($path))
  {
	$is_admin_page = false;
  }
   
  $js_settings = [
    'licence_number'  => $config->get('licence_number'),
	'livechat_mobile' => $config->get('livechat_mobile'),
	'is_admin_page'	  => $is_admin_page
  ];

  $page['#attached']['drupalSettings']['livechat'] = $js_settings;

  $page['#attached']['library'][] = 'livechat/livechat';
  
}

function _livechat_active($path) {
 
  $page_match = false;
  
  if(strpos($path,"admin")){
	  $page_match = true ; 
  }

  return $page_match;
}

function livechat_theme($existing, $type, $theme, $path) {
  $user = \Drupal::currentUser();
  $userName = $user->getUsername();
  $userEmail = $user->getEmail();

  return [
    'livechat_settings' => [
      'variables' => [
      	'userName' => $userName,
		'userEmail' => $userEmail,
		'siteUrl' => $GLOBALS['base_url']
      ]
    ],
  ];
}
